name: Only test, transform, and move files that have been changed

on:
  push:
    branches:
      - feature/bilara-to-sc-action

jobs:
  test-transform-and-move-bilara-data-to-sc-data:
    runs-on: ubuntu-20.04
    
    env:
      FROM_REPO: suttacentral/bilara-data
      FROM_REPO_BRANCH: published
      TO_REPO: suttacentral/sc-data
      TO_REPO_BRANCH: master
      TO_REPO_TARGET_FOLDER: sc_bilara_data
      TEST_REPO: suttacentral/sc-renumber-segments
      TEST_REPO_BRANCH: master
      PYTHON_VERSION: 3.7.5
      STARTING_COMMIT: ${{ github.event.before }}

    steps:
      - name: Checkout ${{ env.TEST_REPO }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TEST_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ env.TEST_REPO_BRANCH }}
          path: sc-renumber-segments

      - name: Checkout ${{ env.FROM_REPO }} repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.FROM_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ env.FROM_REPO_BRANCH }}
          fetch-depth: 0
          path: sc-renumber-segments/bilara-data

      - name: Get commit ID of the last workflow run
        run: |
          workflows=$(curl \
          -H 'Accept: application/vnd.github.v3+json' \
          "https://api.github.com/repos/suttacentral/bilara-data/actions/workflows/bilara-data-changed-files-to-sc-data.yml/runs")
          last_run_conclusion=$(echo $workflows | jq -r '.workflow_runs[1].conclusion')
          echo "Conclusion of last run:"
          echo $last_run_conclusion
          if [[ "$last_run_conclusion" == "failure" ]]
          then
            last_successfull_commit_id=$(echo $workflows | jq -r "first(.workflow_runs[] | select(.conclusion == \"success\")) | .head_commit[\"id\"]")
            echo "STARTING_COMMIT=$last_successfull_commit_id" >> $GITHUB_ENV
          fi

      - name: Get changed files
        id: changed-files
        run: echo ::set-output name=FILES::$(git diff --diff-filter=ACMR --no-commit-id --name-only -r ${{ env.STARTING_COMMIT }}..${{ github.sha }} -- '*.json')
        working-directory: sc-renumber-segments/bilara-data

      - name: Get deleted files
        id: deleted-files
        run: echo ::set-output name=DELETED::$(git diff --diff-filter=D --no-commit-id --name-only -r ${{ env.STARTING_COMMIT }}..${{ github.sha }} -- '*.json')
        working-directory: sc-renumber-segments/bilara-data

      - name: Setup Python
        if: steps.changed-files.outputs.FILES
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Checkout ${{ env.TO_REPO }} repo
        if: steps.changed-files.outputs.FILES || steps.deleted-files.outputs.DELETED
        uses: actions/checkout@v2
        with:
          repository: ${{ env.TO_REPO }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ env.TO_REPO_BRANCH }}
          path: sc-data

      - name: Cache pip
        if: steps.changed-files.outputs.FILES
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install sc-renumber-segments Python dependencies
        if: steps.changed-files.outputs.FILES
        run: pip install -r requirements.txt
        working-directory: sc-renumber-segments

      - name: Set up sutta-processor
        if: steps.changed-files.outputs.FILES
        run: pip install -e .
        working-directory: sc-renumber-segments

      - name: Install bilara-data Python dependencies
        if: steps.changed-files.outputs.FILES
        run: pip install -r requirements.txt
        working-directory: sc-renumber-segments/bilara-data/nilakkhana

      - name: Run Nilakkhana transform only on changed files
        if: steps.changed-files.outputs.FILES
        run: python nilakkhana/per_file_parse.py -f ${{ steps.changed-files.outputs.FILES }}
        working-directory: sc-renumber-segments/bilara-data

      - name: Run sutta-processor
        if: steps.changed-files.outputs.FILES
        run: sutta-processor -c check_all_changes_config.yaml -f ${{ steps.changed-files.outputs.FILES }}
        working-directory: sc-renumber-segments

      - name: Copy changed files to the target directory
        if: steps.changed-files.outputs.FILES
        run: |
          for f in ${{ steps.changed-files.outputs.FILES }}
          do
            mkdir -p $TO_REPO_TARGET_FOLDER/$(dirname $f)
            cp ../sc-renumber-segments/bilara-data/$f $TO_REPO_TARGET_FOLDER/$(dirname $f)/
          done
        working-directory: sc-data

      - name: Remove deleted files from ${{ env.TO_REPO }}
        if: steps.deleted-files.outputs.DELETED
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          for f in ${{ steps.deleted-files.outputs.DELETED }}
          do
            git rm --ignore-unmatch $TO_REPO_TARGET_FOLDER/$f
          done
          git commit -m "Updating sc-bilara-data from bilara-data with deleted files."
          git push
        working-directory: sc-data

      - name: Push changed files to ${{ env.TO_REPO }}
        if: steps.changed-files.outputs.FILES
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updating sc-bilara-data from bilara-data with new or changed files."
          git push
        working-directory: sc-data
